console.error("Iam Error King")
// console.assert(5>10)
// console.assert(510>10)
console.clear()

obj ={a:1,b:2,c:3}
console.table(obj)

console.warn("Hey You Need to complete this JS Cource ")
console.info("Be Consitence ")


//It gives time of loop execution 
console.time("Akib Speed to code!!")
for (let index = 0; index < 5; index++) {
    console.log("JI")
}
console.timeEnd("Akib Speed to code!!")

